services:
  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: random
  searchapi:
    image: ${SEARCHAPI_IMAGE_URI}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  web:
    image: ${WEB_IMAGE_URI}
    ports:
      - "3300:3000"
    depends_on:
      - searchapi
