apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: searchapi
  template:
    metadata:
      labels:
        app: searchapi
    spec:
      containers:
        - name: searchapi
          image: 975050071740.dkr.ecr.us-east-1.amazonaws.com/searchapi:1.1.0
          ports:
            - containerPort: 8080
