apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
spec:
  global:
    site: "us5.datadoghq.com"
    tags:
      - "env:${ENV}"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
