apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: ingress
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /search
            pathType: Exact
            backend:
              service:
                name: searchapi
                port:
                  number: 80
          - path: /crawl
            pathType: Exact
            backend:
              service:
                name: searchapi
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
