apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollouts-lease-access-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argocd
roleRef:
  kind: Role
  name: rollouts-lease-access
  apiGroup: rbac.authorization.k8s.io
