apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollouts-configmap-reader-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: argocd
roleRef:
  kind: Role
  name: rollouts-configmap-reader
  apiGroup: rbac.authorization.k8s.io
