apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web
  namespace: ${NAMESPACE}
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        app.kubernetes.io/instance: web
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: web
          image: "${ECR_REGISTRY}/web:${IMAGE_TAG}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_ENDPOINT
              value: ${API_ENDPOINT}
            - name: NEXTAUTH_URL
              value: ${NEXTAUTH_URL}
            - name: GITHUB_CLIENT_ID
              value: ${GITHUB_CLIENT_ID}
            - name: GITHUB_SECRET
              value: ${GITHUB_SECRET}
            - name: NEXTAUTH_SECRET
              value: ${NEXTAUTH_SECRET}
            - name: GOOGLE_ID
              value: ${GOOGLE_ID}
            - name: GOOGLE_SECRET
              value: ${GOOGLE_SECRET}
  strategy:
    blueGreen:
      activeService: web
      previewService: web-preview
      autoPromotionEnabled: false
      previewReplicaCount: 3
      scaleDownDelaySeconds: 300
