apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DSN: {{ .Values.DSN }}
  REDIS_HOST: {{ .Values.REDIS_HOST | b64enc }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc }}
