apiVersion: v1
kind: Service
metadata:
  name: searchapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: searchapi
---
apiVersion: v1
kind: Service
metadata:
  name: searchapi-preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: searchapi
