apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  MYSQL_DATABASE: {{ .Values.database | b64enc }}
  MYSQL_USERNAME: {{ .Values.username | b64enc }}
  MYSQL_PASSWORD: {{ .Values.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.root_password | b64enc }}
