name: Nightly Build

on:
  push:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build + Test on Temporary Machine
  #       uses: test

  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qa
