name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Helm Charts
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          cluster-name: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
