name: Promote

on:
  workflow_dispatch:
    inputs:
      target-environment:
        type: choice
        description: The environment you are promoting to
        options:
          - uat
          - prod
      searchapi-tag:
        type: string
        description: The tag of the searchapi image being promoted
      web-tag:
        type: string
        description: The tag of the web image being promoted

permissions:
  id-token: write
  contents: read

jobs:
  tag:
    uses: ./.github/workflows/tag.yml
    with:
      target-environment: ${{ inputs.target-environment }}
      searchapi-tag: ${{ inputs.searchapi-tag }}
      web-tag: ${{ inputs.web-tag }}
  deploy:
    needs: tag
    uses: ./.github/workflows/deploy.yml
    with:
      target-environment: ${{ needs.tag.outputs.environment }}
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      GH_SECRET: ${{ secrets.GH_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
